FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip \
    python3-dev \
    pkg-config \
    wget \
    nasm \
    yasm \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
WORKDIR /app
COPY . /app/

# Install project dependencies 
WORKDIR /app/check
RUN pip3 install -e ".[test]"
WORKDIR /app

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["python3 -m pytest"] 